### ISSUE TITLE
Possible performance optimization

### ISSUE THREAD

**Issue by liboyue** [zhunzhong07/IDE-baseline-Market-1501#1]
- Use `my_pdist2 = @(A, B) sqrt( bsxfun(@plus, sum(A.^2, 2), sum(B.^2, 2)') - 2*(A*B') )` instead of `pdist2`. It would speed up this operation 50 times on my Mac.

```
A = rand(1000, 10000);
B = rand(1000, 10000);
sum(sum((my_pdist2(A, B) - pdist2(A, B)).^2))
timeit(@() my_pdist2(A, B))
timeit(@() pdist2(A, B))
```

- Use `parfor` instead of `for` for the main loop in `evaluation.m`. 4x faster at least.

**Comment by zhunzhong07** [comment]
Thanks, we have improved the code according to your proposal.

**Comment by zhunzhong07** [comment]
@liboyue Thanks, we have improved the code according to your proposal.
