### ISSUE TITLE
Multi-query setting for Market-1501 without multiple images per camera for identities in the query set?

### ISSUE THREAD

**Issue by MLenthousiast** [zhunzhong07/IDE-baseline-Market-1501#5]
I wondered what the correct way is to do multi-query on the Market-1501 dataset, since there seems to be no identity in the query part of the test set which has more than 1 image per camera. How does one get those multiple images from a single person from a single camera?

**Comment by zhunzhong07** [comment]
You can follow the evaluation code provided by Market-1501 http://www.liangzheng.org/Project/project_reid.html
