### ISSUE TITLE
how to slove it?

### ISSUE THREAD

**Issue by huangtinglin** [zhunzhong07/IDE-baseline-Market-1501#6]
Training and tesing IDE model
after I did the first step,I still cannot find the IDE models in "out/market_train" 

![image](https://user-images.githubusercontent.com/26502648/33796440-3e7870b0-dd2f-11e7-86b0-c4221d50e459.png)

**Comment by zhunzhong07** [comment]
Do you run the training code on the correct $IDE_ROOT path ?

**Comment by huangtinglin** [comment]
Excuse me, do you mean to put code under the $IDE_ROOT folder?

**Comment by zhunzhong07** [comment]
You should run the training code ./experiments/market/train_IDE_ResNet_50.sh under the $IDE_ROOT folder, then you will achieve IDE models in "out/market_train".
