### ISSUE TITLE
[ask for help]

### ISSUE THREAD

**Issue by lingfengyueguang** [zhunzhong07/IDE-baseline-Market-1501#7]
I want to know what these files to do,which in   IDE-baseline-Market-1501/market_evaluation/data/                                                          (e.g.    testCam.mat ,queryCam.mat,w2c.mat, codebook_350.mat).

**Comment by zhunzhong07** [comment]
These files have the ground truth camera information for each image, for more details, please refer to http://www.liangzheng.org/Project/project_reid.html
