### ISSUE TITLE
training and testing trick problems

### ISSUE THREAD

**Issue by Wayne-Yuan** [zhunzhong07/IDE-baseline-Market-1501#8]
I've been trying to reproduce your reporting results using keras lately. However I had some problems in enhancing mAP, so I thought there might be some missing tricks and checked your code in more detail. And here are my two questions.

1. Is random horizontal flip the only augmentation you use during training? Do I miss something else?
2. Why do you flip the width and height in `prepear_img.m` during testing when extracting features?

**Comment by zhunzhong07** [comment]
Hi @hardtopickupname ，
1. We use both random crop and random flip during training.
2. since the width and height in Matlab are opposite to the format in Caffe, so we first reverse them for extracting features.

**Comment by Wayne-Yuan** [comment]
Hi, thank you for your explanation. I got the second point, but your `crop_size` in `transform_param` equals to `new_height` and `new_width` in `image_data_param`, I am not that familiar with caffe, so does random crop still function?

**Comment by zhunzhong07** [comment]
I am sorry that in this version, we did not perform random crop. But in your keras code, you can add random crop during training, it will obtain better perfromance.

**Comment by Wayne-Yuan** [comment]
Alright, thank you so much.

**Comment by zhunzhong07** [comment]
You can also improve the performance with our [random erasing](https://github.com/zhunzhong07/Random-Erasing) during training, and [k-reciprocal re-ranking](https://github.com/zhunzhong07/person-re-ranking).
